@startuml



class Camera {
	+Camera()
    +~Camera()
    +GetEye() : glm::vec3
    +GetAt() : glm::vec3
    +GetWorldUp() : glm::vec3
    +GetViewMatrix() : glm::mat4
    +GetProj() : glm::mat4
    +GetViewProj() : glm::mat4
    +SetView(glm::vec3 _eye, glm::vec3 _at, glm::vec3 _up) : void
    +GetAngle() : float
    +SetAngle(const float _angle) : void
    +GetAspect() : float
    +SetAspect(const float _aspect) : void
    +GetZNear() : float
    +SetZNear(const float _zn) : void
    +GetZFar() : float
    +SetZFar(const float _zf) : void
    +SetProj(float _angle, float _aspect, float _zn, float _zf) : void
    -m_eye : glm::vec3
    -m_worldUp : glm::vec3
    -m_at : glm::vec3
    -m_viewMatrix : glm::mat4
    -m_zNear : float
    -m_zFar : float
    -m_angle : float
    -m_aspect : float
    -m_projMatrix : glm::mat4
}



@enduml
