@startuml



class Framebuffer {
    +Framebuffer(unsigned width, unsigned height)
    +~Framebuffer()
    +Bind() : void
    +UnBind() : void
    +Blit() : void
    +Resize(unsigned width, unsigned height) : void
    +Screenshot(const std::filesystem::path& screenshot_path) : void
    -m_width : unsigned
    -m_height : unsigned
    -m_framebuffer_id : GLuint
    -m_target_texture : Texture2D
    -Init() : void
    -FlipSDLSurface(SDL_Surface* surface) : void
}



@enduml
