@startuml



class Texture2D {
	+Texture2D(unsigned width, unsigned height, GLenum format, unsigned levels)
	+~Texture2D()
	+Resize(unsigned width, unsigned height) : void
	+Resize(unsigned width, unsigned height, unsigned levels) : void
	+GetTextureID() : GLuint
	+Bind(GLuint unit, GLenum access, unsigned level) : void
	-m_texture_id : GLuint
	-m_width : unsigned
	-m_height : unsigned
	-m_format : GLenum
	-m_levels : unsigned
	-Init() : void
}



@enduml
